import {readFile} from 'node:fs/promises';
import {pageCsp} from './services/page-security.mjs';
import Fastify from 'fastify';
import fastifyStatic from '@fastify/static';
import {createSessionService} from './services/session-service.mjs';
import {registerSessionRoutes} from './services/session-routes.mjs';
import {createReportService} from './services/report-service.mjs';
import {appendFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const csp=pageCsp(await readFile(new URL('./dist/index.html',import.meta.url),'utf8'));
const app=Fastify({logger:true,bodyLimit:8192,trustProxy:false});
const root=path.dirname(fileURLToPath(import.meta.url));
const data=process.env.DATA_DIR||path.join(root,'data');await mkdir(data,{recursive:true});
app.addHook('onSend',async(req,reply,payload)=>{const pathname=req.url.split('?')[0];if(pathname.startsWith('/api/'))reply.header('Cache-Control','no-store');else if(['GET','HEAD'].includes(req.method)&&reply.statusCode<400){if(/^\/(assets|backgrounds|portraits|music)\//.test(pathname))reply.header('Cache-Control','public, max-age=31536000, immutable');else reply.header('Cache-Control',pathname==='/'||pathname==='/sanguo'||pathname.endsWith('.html')?'no-cache':'no-store');}reply.header('X-Content-Type-Options','nosniff').header('Referrer-Policy','same-origin').header('X-Frame-Options','DENY').header('Content-Security-Policy',csp);return payload;});
const reports=createReportService({dataDir:data,cacheReports:false,apiKey:process.env.GLM_API_KEY,endpoint:process.env.GLM_ENDPOINT,model:process.env.GLM_MODEL,enabled:process.env.LLM_ENABLED==='true',logger:app.log});
app.get('/api/health',async()=>({ok:true,version:'0.3.0',llmEnabled:process.env.LLM_ENABLED==='true'&&!!process.env.GLM_API_KEY}));
const sessions=createSessionService({dataDir:data,reports,model:process.env.GLM_MODEL});
app.get('/api/v1/quiz/sanguo/session',async(_req,reply)=>reply.code(410).send({error:'请刷新页面，使用新的专属链接开始。'}));
app.post('/api/v1/quiz/sanguo/submit',async(_req,reply)=>reply.code(410).send({error:'请刷新页面，使用新的专属链接提交。'}));
const allowed=new Set(['quiz_start','answer','quiz_complete','report_open','share_download','share_copy']);
app.post('/api/v1/events',async(req,reply)=>{const {name,properties}=req.body||{};if(!allowed.has(name))return reply.code(400).send({error:'Invalid event'});const entry={name,time:new Date().toISOString()};if(name==='answer'&&Number.isInteger(properties?.question)&&properties.question>=1&&properties.question<=18)entry.question=properties.question;await appendFile(path.join(data,'events.jsonl'),JSON.stringify(entry)+'\n');return {ok:true};});
await app.register(fastifyStatic,{root:path.join(root,'dist'),preCompressed:true,setHeaders(res,file){const name=file.replace(/\.(br|gz)$/,'');res.setHeader('Cache-Control',name.endsWith('.html')?'no-cache':'public, max-age=31536000, immutable');res.setHeader('Vary','Accept-Encoding');}});
await registerSessionRoutes(app,{sessions});
app.setNotFoundHandler((req,reply)=>{if(req.url.startsWith('/api/'))return reply.code(404).send({error:'Not found'});return reply.code(404).send({error:'页面不存在，请返回首页'});});
await app.listen({port:Number(process.env.PORT||3000),host:process.env.HOST||'127.0.0.1'});
